// Generated by `node scripts/showreel-voice.mjs sync <take.mp3>`: cut times
// and in-shot beats measured from the recorded voiceover. Delete the values
// (set VO_SYNC to null) to fall back to the hand-set timing in timeline.ts.

export type VoSync = {
  /** Source take the timing was measured from. */
  source: string;
  /** Shot start times in seconds. */
  shots: Record<string, number>;
  /** In-shot beat overrides (seconds after the shot start). */
  beats: Record<string, Record<string, number>>;
  /** Where each voice line starts on the timeline, and how long it runs. */
  cues: Array<{line: number; at: number; len: number}>;
  /** End of the film in seconds. */
  end: number;
};

export const VO_SYNC: VoSync | null = null;
