// Generated by `node scripts/showreel-voice.mjs sync voiceover/raw/kavox_vo_elevenlabs_v4_amanda.mp3`: cut times
// and in-shot beats measured from the recorded voiceover. Set VO_SYNC to null
// to fall back to the hand-set timing in timeline.ts.

export type VoSync = {
  /** Source take the timing was measured from. */
  source: string;
  /** Shot start times in seconds. */
  shots: Record<string, number>;
  /** In-shot beat overrides (seconds after the shot start). */
  beats: Record<string, Record<string, number>>;
  /** Where each voice line starts on the timeline, and how long it runs. */
  cues: Array<{line: number; at: number; len: number}>;
  /** End of the film in seconds. */
  end: number;
};

export const VO_SYNC: VoSync | null = {
  "source": "kavox_vo_elevenlabs_v4_amanda.mp3",
  "shots": {
    "intro": 0,
    "nacht": 5,
    "baustelle": 12.22,
    "sagen": 17.22,
    "rechenweg": 27.51,
    "unterschrift": 35.41,
    "uebergabe": 41.55,
    "pruefen": 46.15,
    "cockpit": 51.65,
    "cashflow": 57.15,
    "befehl": 61.75,
    "archiv": 68.3,
    "outro": 74.12
  },
  "beats": {
    "sagen": {
      "typeStart": 0.35,
      "typeEnd": 5.84,
      "fertig": 6.15,
      "reply": 6.04,
      "card": 6.39,
      "pan": 6.14,
      "panEnd": 7.74,
      "count": 7.69
    },
    "rechenweg": {
      "zoom": 0.2,
      "lift": 0.6,
      "line1": 0.71,
      "line2": 2.27,
      "line3": 2.98,
      "result": 3.73
    },
    "unterschrift": {
      "count": 0.4,
      "countEnd": 2.3,
      "pulse": 3.6
    },
    "uebergabe": {
      "tap": 0.5,
      "fly": 0.85,
      "land": 1.85,
      "settle": 2.6
    },
    "pruefen": {
      "check1": 0.4,
      "checkEvery": 0.38,
      "pan": 1.15,
      "sweep": 1.85,
      "pdf": 2.31,
      "stripes": 2.81,
      "send": 3.71
    },
    "cockpit": {
      "type": 0.25,
      "cards": 0.75,
      "cardEvery": 0.16,
      "offen": 2.11,
      "ueberfaellig": 2.97
    },
    "cashflow": {
      "draw": 0.35,
      "drawEnd": 3.35
    },
    "befehl": {
      "keys": 0.1,
      "press": 2.16,
      "palette": 2.56,
      "type": 2.96,
      "typeEvery": 0.12,
      "rows": 3.31
    },
    "archiv": {
      "left": 0,
      "right": 0.15,
      "count": 0.35,
      "countEnd": 1.55,
      "zahldauer": 0.85,
      "excel": 1.94,
      "griff": 4.55
    },
    "outro": {
      "offline": 0.3,
      "collapse": 4.34,
      "logo": 4.64,
      "tagline": 5.76
    }
  },
  "cues": [
    {
      "line": 1,
      "at": 5.35,
      "len": 6.52
    },
    {
      "line": 2,
      "at": 12.57,
      "len": 2.65
    },
    {
      "line": 3,
      "at": 17.57,
      "len": 6.36
    },
    {
      "line": 4,
      "at": 27.86,
      "len": 7.2
    },
    {
      "line": 5,
      "at": 35.76,
      "len": 5.45
    },
    {
      "line": 6,
      "at": 41.9,
      "len": 8.54
    },
    {
      "line": 7,
      "at": 52,
      "len": 7.14
    },
    {
      "line": 8,
      "at": 62.1,
      "len": 5.84
    },
    {
      "line": 9,
      "at": 68.65,
      "len": 5.13
    },
    {
      "line": 10,
      "at": 74.47,
      "len": 3.84
    },
    {
      "line": 11,
      "at": 78.87,
      "len": 3.16
    }
  ],
  "end": 83.62
};
